/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/views/**/*.ejs', './public/js/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#2d3136',
        'secondary-fixed-dim': '#b7c8e2',
        'surface-dim': '#101419',
        'surface-container-high': '#262a30',
        'surface-bright': '#36393f',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'on-tertiary': '#4f2500',
        'outline-variant': '#414753',
        primary: '#abc7ff',
        'surface-container-highest': '#31353b',
        'primary-fixed': '#d7e2ff',
        'primary-container': '#458fff',
        'on-secondary-fixed-variant': '#38485d',
        success: '#2DD4A8',
        tertiary: '#ffb782',
        'on-secondary': '#213146',
        'surface-container': '#1c2025',
        'inverse-primary': '#005cbc',
        'text-on-dark': '#E7ECF3',
        background: '#101419',
        'on-primary-fixed-variant': '#004590',
        'tertiary-container': '#de7507',
        surface: '#141A22',
        'on-tertiary-container': '#452000',
        'on-primary-fixed': '#001b3f',
        'on-secondary-container': '#a9b9d3',
        'border-muted': '#2A3548',
        'inverse-surface': '#e0e2ea',
        'secondary-container': '#3a4a60',
        'surface-container-low': '#181c21',
        outline: '#8b919f',
        'on-surface-variant': '#c1c6d6',
        'on-primary-container': '#00285a',
        'on-secondary-fixed': '#0b1c30',
        'on-primary': '#002f66',
        'surface-elevated': '#1A2330',
        'surface-container-lowest': '#0a0e13',
        'on-surface': '#e0e2ea',
        secondary: '#b7c8e2',
        error: '#F07178',
        'surface-tint': '#abc7ff',
        'tertiary-fixed-dim': '#ffb782',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'max-width': '1120px',
        '2xl': '32px',
        gutter: '20px',
        sm: '8px',
        lg: '16px',
        xl: '24px',
        xs: '4px',
        md: '12px',
        '3xl': '48px',
      },
      fontFamily: {
        'body-lg': ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        'label-sm': ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        'display-lg': ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        'body-md': ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        'headline-md': ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        sans: ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['28px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '21px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '25px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      maxWidth: {
        'max-width': '1120px',
      },
    },
  },
  plugins: [],
};
